### ISSUE TITLE
url configuration

### ISSUE THREAD

**Issue by stdavis** [agrc/ironing-board#109] opened 2016-12-08 15:45 UTC
As a user I want the application to be presented to me based on the URL I come from so I can be presented with the sure sites information.

EDC wants a link that will automatically open the sure sites section (including filters) and turn on the sure sites points.

**Comment by steveoh** [comment] 2016-12-08 21:44
Would this be a duplicate of #96?

**Comment by stdavis** [comment] 2016-12-08 23:30
I would say that this supersedes #96.

**Closed** 2017-02-28 17:42 UTC
Labels: 5 hr, low priority
